-- Insert UP districts
INSERT INTO districts (name, state, district_code) VALUES
('Agra', 'Uttar Pradesh', 'UP_AGRA'),
('Aligarh', 'Uttar Pradesh', 'UP_ALIGARH'),
('Ambedkar Nagar', 'Uttar Pradesh', 'UP_AMBEDKAR_NAGAR'),
('Amethi', 'Uttar Pradesh', 'UP_AMETHI'),
('Amroha', 'Uttar Pradesh', 'UP_AMROHA'),
('Azamgarh', 'Uttar Pradesh', 'UP_AZAMGARH'),
('Ballia', 'Uttar Pradesh', 'UP_BALLIA'),
('Banda', 'Uttar Pradesh', 'UP_BANDA'),
('Bareilly', 'Uttar Pradesh', 'UP_BAREILLY'),
('Basti', 'Uttar Pradesh', 'UP_BASTI'),
('Deoria', 'Uttar Pradesh', 'UP_DEORIA'),
('Fatehpur', 'Uttar Pradesh', 'UP_FATEHPUR'),
('Ghaziabad', 'Uttar Pradesh', 'UP_GHAZIABAD'),
('Gorakhpur', 'Uttar Pradesh', 'UP_GORAKHPUR'),
('Jaunpur', 'Uttar Pradesh', 'UP_JAUNPUR'),
('Kanpur Nagar', 'Uttar Pradesh', 'UP_KANPUR_NAGAR'),
('Lucknow', 'Uttar Pradesh', 'UP_LUCKNOW'),
('Meerut', 'Uttar Pradesh', 'UP_MEERUT'),
('Mirzapur', 'Uttar Pradesh', 'UP_MIRZAPUR'),
('Moradabad', 'Uttar Pradesh', 'UP_MORADABAD'),
('Prayagraj', 'Uttar Pradesh', 'UP_PRAYAGRAJ'),
('Varanasi', 'Uttar Pradesh', 'UP_VARANASI'),
('Sultanpur', 'Uttar Pradesh', 'UP_SULTANPUR'),
('Unnao', 'Uttar Pradesh', 'UP_UNNAO'),
('Sitapur', 'Uttar Pradesh', 'UP_SITAPUR'),
('Hardoi', 'Uttar Pradesh', 'UP_HARDOI'),
('Raebareli', 'Uttar Pradesh', 'UP_RAEBARELI'),
('Farrukhabad', 'Uttar Pradesh', 'UP_FARRUKHABAD'),
('Etawah', 'Uttar Pradesh', 'UP_ETAWAH'),
('Mainpuri', 'Uttar Pradesh', 'UP_MAINPURI')
ON CONFLICT (district_code) DO NOTHING;
